### ISSUE TITLE
Pawarumi - CUSA18128

### ISSUE THREAD

**Issue by Stosbaby** [red-prig/fpps4-game-compatibility#1158]
# Pawarumi 

## Game version
1.00

## Used emulator's version
red-prig/fpPS4@9e3d998

## Current status
Nothing

An unhandled exception occurred
An unhandled exception occurred at $0000000100083350:
EAssertionFailed: TODO tiling_idx:Thick_1dThick (vImageTiling.pas, line 498)
  $0000000100083350
  $00000001000796E4
  $000000010007A39D
  $000000010007A910
  $0000000100076844
  $00000001000051E6
  $00000001000145B1
  $00007FFD580426BD
  $00007FFD5966DFB8

An unhandled exception occurred at $00000001002147FB:
EAccessViolation: Access violation

## Description
From the logs, it's the file ( picture 1 ) which is the problem ( i thnk ). Before that, I added "libSceSaveData".

## Screenshots
![image](https://user-images.githubusercontent.com/57594354/212494774-22f577fb-1f32-48c2-85b3-b72c3bb69f83.png)
![image](https://user-images.githubusercontent.com/57594354/212494836-167fad00-3e9c-4cb5-9e42-7572d93c287b.png)

**Comment by ArbestRi** [comment]
Try with SKIP_UNKNOW_TILING
