### ISSUE TITLE
Unturned- CUSA19101

### ISSUE THREAD

**Issue by Stosbaby** [red-prig/fpps4-game-compatibility#1163]
# Game name
Unturden

## Code
CUSA19101

## Game version
1.00

## Used emulator's version
red-prig/fpPS4@9e3d998

## Current status
Nothing

## Error
nop nid:libScePosix:4D4FDDF4F7C81CF3:socket

**Comment by B8nee** [comment]
I advise you to change the name of the game both in the title and in the issue because the code CUSA19101 shows the name of the game "Unturned" not "Unterned". I gave you this advice to make it easier for people who want to check the status of this game to find the game

**Comment by Stosbaby** [comment]
Thanks you it's mistake.
Done

**Comment by B8nee** [comment]
No problem, just look again the game name in the post and it's perfect!
