### ISSUE TITLE
Terraria - CUSA

### ISSUE THREAD

**Issue by Leaziurd** [red-prig/fpps4-game-compatibility#1222]
# Game name
Terraria 

## Code
CUSA

## Game version
1.00

## Used emulator's version
red-prig/fpPS4@

## Error
An unhandled exception occurred at $0000000100110E60:
EAssertionFailed: sparse not support for host (vHostBufferManager.pas, line 263)
  $0000000100110E60
  $0000000100076603
  $0000000100079AC0
  $0000000100075B54
  $0000000100005166
  $00000001000144D1
  $00007FF826CD26BD
  $00007FF827A8DFB8

**Comment by Squidtito** [comment]
This post already exists, https://github.com/red-prig/fpps4-game-compatibility/issues/93

Close this please.
