### ISSUE TITLE
Conan Chop Chop - CUSA16299

### ISSUE THREAD

**Issue by RyzenDew** [red-prig/fpps4-game-compatibility#1266]
# Conan Chop Chop

## Code
CUSA16299

## Game version
1.00

## Used emulator's version
red-prig/fpPS4@476be42

## Current status
Booting and has audio

## Error
None

## Description
Boot's up no extra library's needed i hear audio then it does nothing.

## Screenshots
![image](https://user-images.githubusercontent.com/84041391/217110765-eadb2b97-4c47-4a37-9c0b-0d54f1b49daa.png)

## Log
[log_CUSA16299.txt](https://github.com/red-prig/fpps4-game-compatibility/files/10670046/log_CUSA16299.txt)

**Comment by ArbestRi** [comment]
Duplicate of #1207
