### ISSUE TITLE
Driveclub - CUSA003

### ISSUE THREAD

**Issue by Raresrcc** [red-prig/fpps4-game-compatibility#1274]
# Game name
Driveclub

## Code
CUSA-003

## Game version
1.28

## Used emulator's version
red-prig/fpPS4@

## Error
```
An unhandled exception occurred
``` 

## Description
Just stays on a white screen. The game might not be compatible. I am using temmie's launcher. I really want to play driveclub with all the dlcs (because the game and all of its associated dlc is not available anymore). I hope someone can help. Thanks!

**Comment by ArbestRi** [comment]
"The game might not be compatible." Because it actually isn't!

**Comment by ArbestRi** [comment]
It isn't like this emulator is in its maturity.
