### ISSUE TITLE
DELTARUNE Chapter 1

### ISSUE THREAD

**Issue by ahmu0911** [red-prig/fpps4-game-compatibility#1302]
DELTARUNE Chapter 1

## Game version
V 0.101

## Used emulator's version
red-prig/fpPS4@

## Current status
Playable, without any hacks. Getting around 15-20 fps, which is enough for this type of game.

## Error
No errors, whatsoever

## Description
Indie game released in 2018, has multiple chapters.

## Screenshots
![Screenshot 2023-02-12 195301](https://user-images.githubusercontent.com/125214560/218331039-67cc14f6-02b6-46fc-886e-8a9856f51a24.png)

**Comment by Kimieggie** [comment]
Invalid format and Duplicate @gandalfthewhite19890404 please close
