### ISSUE TITLE
Zombieland Double Tap - Road Trip - CUSA15438

### ISSUE THREAD

**Issue by GAMERRPCS3** [red-prig/fpps4-game-compatibility#1321]
# Game name
Zombieland Double Tap - Road Trip

## Code 
CUSA15438

## Game version 
1.00

## Used emulator's version 
red-prig/fpPS4@605c24c 

## Current status 
starts

# Error

vkQueueSubmit:VK_ERROR_DEVICE_LOST

## 

## Description 
the game progresses differently depending on the Hack you use. to almost get to the menu.

## Screenshots 

![Capture d’écran 2023-03-05 165209](https://user-images.githubusercontent.com/121258975/222974229-11e83746-23b1-4fea-a810-dd80ab6e81c0.png)

![Capture d’écran 2023-03-05 165428](https://user-images.githubusercontent.com/121258975/222974265-10769de4-ebbb-4c2f-acbe-73c9ff1bf3c4.png)

![Capture d’écran 2023-03-05 164928](https://user-images.githubusercontent.com/121258975/222974279-f24fa429-4c8b-44ec-bde0-8e46b5622476.png)

**Comment by Kimieggie** [comment]
Fix title and add fpPS4 version

**Comment by Jerome2b39** [comment]
Voila ce que mon ami à utilisé Comme Hack 

DEPTH DISABLE HACK - COMPUTE DISABLE HACK 
DISABLE SRGB HACK - DISABLE FMV HACK 
ENABLE SKIP UNKNOW TILING

**Comment by and468860** [comment]
repeater closes
