### ISSUE TITLE
Golf Club Wasteland - CUSA27458

### ISSUE THREAD

**Issue by GAMERRPCS3** [red-prig/fpps4-game-compatibility#1333]
# Game name
Golf Club Wasteland

## Code
CUSA27458

## Game version
1.02

## Used emulator's version
red-prig/fpPS4@13f5696

## Current status
starts 

## Error
vkAllocateMemory:VK_ERROR_OUT_OF_DEVICE_MEMORY
An unhandled exception occurred at $00000001000BE324:
EAssertionFailed: Assertion failed (vMemory.pas, line 684)
  $00000001000BE324
  $00000001000946D9
  $000000010013E46B
  $000000010013E97F
  $0000000100135644
  $0000000100135812
  $000000010008E934
  $000000010008EEB0
  $000000010008AE04
  $0000000100005046
  $00000001000144E1
  $00007FF889817614
  $00007FF889B426A1

## Description
DEPTH DISABLE HACK - COMPUTE DISABLE HACK - Enable DISABLE_SRGB_HACK - DISABLE FMV HACK - Enable SKIP_UNKNOW_TILING

## Screenshots

![Capture d’écran 2023-03-06 013037](https://user-images.githubusercontent.com/121258975/222995259-803ab6e3-eb8d-443c-8a26-1f501e9d588b.png)

![Capture d’écran 2023-03-06 012135](https://user-images.githubusercontent.com/121258975/222995208-3b207171-e616-48dd-b251-a2d3284f8cbb.png)

![Capture d’écran 2023-03-06 012106](https://user-images.githubusercontent.com/121258975/222995216-3d896f01-b2ec-4c8e-8b96-6e12c46e8953.png)

**Comment by and468860** [comment]
repeater closes
