### ISSUE TITLE
METAL GEAR SURVIVE - CUSA07150

### ISSUE THREAD

**Issue by GAMERRPCS3** [red-prig/fpps4-game-compatibility#1336]
# Game name
METAL GEAR SURVIVE

## Code
CUSA07150

## Game version
1.00

## Used emulator's version
red-prig/fpPS4@13f5696

## Current status
starts

## Error
[main:17704] nop nid:libkernel:1E4EE21E61B1075F:ipmimgr_call

## Description
white window

## Screenshots

![Capture d’écran 2023-03-06 020743](https://user-images.githubusercontent.com/121258975/222997773-a9791910-c151-4fc5-9bdc-2ede291ad4ea.png)

![Capture d’écran 2023-03-06 013037](https://user-images.githubusercontent.com/121258975/222997786-f7393c8c-374e-4cc3-a181-946ce7170b22.png)

![Capture d’écran 2023-03-06 015902](https://user-images.githubusercontent.com/121258975/222997800-56fa3f5d-407e-4236-83a6-6702c43091be.png)

**Comment by and468860** [comment]
repeater closes
