### ISSUE TITLE
 Resident Evil HD Remaster  - CUSA01067

### ISSUE THREAD

**Issue by GAMERRPCS3** [red-prig/fpps4-game-compatibility#1337]
# Game name
 Resident Evil HD Remaster 

## Code
CUSA01067

## Game version
1.00

## Used emulator's version
red-prig/fpPS4@13f5696

## Current status
starts

## Error

[main:5152] nop nid:libSceNpParty:9616024D098191DB:sceNpPartyInitialize

## Description
starts white window

## Screenshots

![Capture d’écran 2023-03-06 030750](https://user-images.githubusercontent.com/121258975/223003896-e4446103-8083-44d1-8328-0bb16c6ddeab.png)

![Capture d’écran 2023-03-06 030726](https://user-images.githubusercontent.com/121258975/223003908-9be96c7d-ef67-4407-91b3-84503c418ab2.png)

![Capture d’écran 2023-03-06 030804](https://user-images.githubusercontent.com/121258975/223003915-3104b5e4-60b6-4110-9eb1-017614de2356.png)

**Comment by and468860** [comment]
repeater closes

**Comment by GAMERRPCS3** [comment]
I copied the module, show in console from first test. and now the error has changed.

![1](https://user-images.githubusercontent.com/121258975/224874206-b1a962cb-5b6a-4961-8d5a-c3d46c9f0505.png)

**Comment by gandalfthewhite19890404** [comment]
Do not copy any libs, except whitelisted. Also - you're no need to report here, there is another issue with this game.

**Comment by GAMERRPCS3** [comment]
All right.
