### ISSUE TITLE
Conan Exiles - CUSA10486

### ISSUE THREAD

**Issue by GAMERRPCS3** [red-prig/fpps4-game-compatibility#1338]
# Game name
Conan Exiles

## Code
CUSA10486

## Game version
1.00

## Used emulator's version
red-prig/fpPS4@13f5696

## Current status
Nothing

## Error
[main:17936] nop nid:libkernel:A8249FA8320B967B:sceKernelMemoryPoolExpand

## Description
Nothing

## Screenshots

![Capture d’écran 2023-03-06 053755](https://user-images.githubusercontent.com/121258975/223020643-1c67104e-a15f-4f0f-a9c3-802061fce08d.png)

![Capture d’écran 2023-03-06 053625](https://user-images.githubusercontent.com/121258975/223020656-3002ab3b-3017-4d05-b3f6-cd6294b89099.png)

**Comment by and468860** [comment]
repeater closes
