### ISSUE TITLE
Lost Worlds Beyond the Page CUSA13908

### ISSUE THREAD

**Issue by zecoxao** [red-prig/fpps4-game-compatibility#1394]
### Game Name

Lost Worlds Beyond the Page

### Game code

CUSA13908

### Game version

1.01

### Used emulator's version

red-prig/fpPS4@af25023

### Current status

Nothing

### Error

[main:8484] nop nid:libc:6F3404C72D7CF592:_init_env

### Description

Hangs with [main:8484] nop nid:libc:6F3404C72D7CF592:_init_env

**Comment by ArbestRi** [comment]
Use libc.prx

**Comment by Kimieggie** [comment]
> Use libc.prx

DON'T use un whitelisted libs

**Comment by zecoxao** [comment]
if i use libc it hangs after with 
[main:14528] nop nid:libSceFios2:C35DCE8E6ECE37DA:sceFiosFHOpenWithModeSync

**Comment by Kimieggie** [comment]
you should never write reports here with non whitelisted libs. If you do they will be deemed invalid @ArbestRi

**Comment by ArbestRi** [comment]
Okay. 😑

**Comment by ArbestRi** [comment]
Duplicate of #1184

**Comment by zecoxao** [comment]
closing then.
