### ISSUE TITLE
AdVenture Capitalist - CUSA06312

### ISSUE THREAD

**Issue by ArbestRi** [red-prig/fpps4-game-compatibility#1425]
### Game Name

AdVenture Capitalist

### Game code

CUSA06312

### Game version

1.00

### Used emulator's version

fef3d27

### Current status

Ingame

### Error

No error

### Description

Glitchy audio. Also, this is the US version, not the EU version.

### Used hacks

DEPTH_DISABLE_HACK, COMPUTE_DISABLE_HACK, SKIP_UNKNOW_TILING

### Screenshots

![Screenshot 2023-03-12 133506](https://user-images.githubusercontent.com/86171223/224572522-02b23821-610a-465c-b94a-b11050f1f5e5.png)
![Screenshot 2023-03-12 133628](https://user-images.githubusercontent.com/86171223/224572523-a7ca02b3-d7e2-4420-85d6-7de1b70fb623.png)

**Comment by Kimieggie** [comment]
duplicate, close

**Comment by Hermiten** [comment]
> duplicate, close

"US version, not EU"

**Comment by Kimieggie** [comment]
> > duplicate, close
> 
> "US version, not EU"
> 
> Is the CUSA same or is it a mistake?

the CUSA is the same so it's duplicate

**Comment by Kimieggie** [comment]
![image](https://user-images.githubusercontent.com/64313946/224574360-85408937-16d4-476e-976d-084ce1c49c33.png)
