### ISSUE TITLE
Salt and Sanctuary - CUSA02353

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [red-prig/fpps4-game-compatibility#143]
### **Game name**
Salt and Sanctuary

### **Code**
CUSA02353

### **Used emulator's version**
https://github.com/red-prig/fpPS4/commit/c20d02a1b9376f8bf5b5ead48b05f7112d18ec43

### **Current status**
Nothing

### **Error** 

```
nop nid:libSceAudiodec:56386C9B1A5C7B32:sceAudiodecInitLibrary
```

### **Description** 
Nothing

### **Screenshots**

**Comment by GamingDuckingalt** [comment]
remove the labels since the issue is a duplicate
