### ISSUE TITLE
STREET FIGHTER V - CUSA01222

### ISSUE THREAD

**Issue by GAMERRPCS3** [red-prig/fpps4-game-compatibility#1435]
### Game Name

STREET FIGHTER V

### Game code

CUSA01222

### Game version

01.00

### Used emulator's version

def590c

### Current status

Boots

### Error

[RHIThread:11684] nop nid:libSceGnmDriver:1541C6F2C437479F:sceGnmSetEsShader

### Description

Nothing

### Screenshots

![1](https://user-images.githubusercontent.com/121258975/226205420-cd7dea04-f158-4bd4-ba92-fff5589dab47.png)
![2](https://user-images.githubusercontent.com/121258975/226205427-edda1d22-72d6-42de-a17a-a664ed5efa9d.png)
![3](https://user-images.githubusercontent.com/121258975/226205433-552c92b6-8fc4-499f-91e3-5911a46e7998.png)

**Comment by GAMERRPCS3** [comment]
sorry i forgot to look that the game has already been tested.

**Comment by Kimieggie** [comment]
> sorry i forgot to look that the game has already been tested.

yeah just close the issue
