### ISSUE TITLE
EA Sports UFC 4 - CUSA14209 

### ISSUE THREAD

**Issue by Jeffy101s** [red-prig/fpps4-game-compatibility#1455]
### Game Name

EA SPORTS UFC 4

### Game code

CUSA14209

### Game version

04.02

### Used emulator's version

5fa656d

### Current status

Nothing

### Error

nop nid:libkernel:81E0DAAA01FD9538:scePthreadKeyCreate

### Description

Please fix this error I don’t feel like buying a ps4 nop nid:libkernel:81E0DAAA01FD9538:scePthreadKeyCreate

**Comment by ArbestRi** [comment]
Duplicate of #418
