### ISSUE TITLE
God Of War RAGNAROK

### ISSUE THREAD

**Issue by larue654** [red-prig/fpps4-game-compatibility#1465]
### Game Name

God Of War RAGNAROK

### Game code

CUSA34384

### Game version

3.02

### Used emulator's version

red-prig/fpPS4@

### Current status

Nothing

### Error

Exception at 0000000100004979: EAccessViolation:
Access violation.

### Description

when i start the game this code appears and don't start the game

**Comment by Kimieggie** [comment]
@gandalfthewhite19890404 duplicate close
