### ISSUE TITLE
Beat Saber (1.00) - CUSA12878

### ISSUE THREAD

**Issue by ItsKaitlyn03** [red-prig/fpps4-game-compatibility#1466]
### Game Name

Beat Saber

### Game code

CUSA12878

### Game version

1.00

### Used emulator's version

6e5a849

### Current status

Nothing

### Error

nop nid:libSceLoginDialog:A8FFC4BD0465D877:sceLoginDialogInitialize

### Description

This game is a PSVR game, maybe when a few PSVR games start working an OpenVR/XR backend should be considered?

**Comment by Kimieggie** [comment]
Duplicate @gandalfthewhite19890404 close
