### ISSUE TITLE
FIFA 22 CUSA27106

### ISSUE THREAD

**Issue by nikodem9002** [red-prig/fpps4-game-compatibility#1479]
### Game Name

fifa 22

### Game code

CUSA27106

### Game version

01.00

### Used emulator's version

1.2.1

### Current status

Playable

### Error

nop nid:libkernel:9EEE1AD3F6AB422B:sceKernelAioInitializeParam

### Description

e

### Screenshots

e

### Log File

e

**Comment by red-prig** [comment]
@nikodem9002 anyway, it's still a duplicate
