### ISSUE TITLE
Hatsune Miku Project Diva X HD - CUSA02908

### ISSUE THREAD

**Issue by fanggeyu** [red-prig/fpps4-game-compatibility#1608]
### Game Name

Hatsune Miku Project Diva X HD

### Game code

CUSA02908

### Game version

01.00

### Used emulator's version

24e4ad1

### Current status

Nothing

### Error

[main:23844] nop nid:libkernel:1E4EE21E61B1075F:ipmimgr_call

### Description

Game shows black screen

**Comment by KimieStar** [comment]
@gandalfthewhite19890404 please close it's a clone
