### ISSUE TITLE
Bloodborne Game of the Year Edition - CUSA03173

### ISSUE THREAD

**Issue by CarlBraun** [red-prig/fpps4-game-compatibility#1635]
### Game Name

Bloodborne

### Game code

CUSA03173

### Game version

v1.09

### Used emulator's version

0.0.1

### Current status

Playable

### Error

nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue

### Description

in Console:
nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue

### Log File

[log.txt](https://github.com/red-prig/fpps4-game-compatibility/files/11901127/log.txt)

**Comment by KimieStar** [comment]
@gandalfthewhite19890404 close duplicate
