### ISSUE TITLE
Gran Turismo Sport - CUSA03220

### ISSUE THREAD

**Issue by XoX02308** [red-prig/fpps4-game-compatibility#1637]
### Game Name

Gran Turismo Sport

### Game code

CUSA03220

### Game version

01.00

### Used emulator's version

1.2.1

### Current status

Nothing

### Error

when I select gran tourismo from the game list, a warning comes in the green tekst saying 

WARN - Unable to locate playgo-chunk.dat for Gran Tourismo!
![image](https://github.com/red-prig/fpps4-game-compatibility/assets/138152351/e665de18-5c07-4730-8e27-12a34019a280)

### Description

When i try to start the game, command prompt does the thing but it doesn't launch gran tourismo.

I have just installed everything today with this youtube video: https://www.youtube.com/watch?v=o1g0B9uusWw

Enabling hacks doesn't do anything

### Screenshots

![image](https://github.com/red-prig/fpps4-game-compatibility/assets/138152351/6b2b2d53-13e3-4ca8-89bb-c28e9086f3cb)
The command prompt shows with every single thing "warn^ -"

**Comment by KimieStar** [comment]
Fix your title please

**Comment by red-prig** [comment]
Fixed

**Comment by red-prig** [comment]
Wrongly unpacked game

**Comment by XoX02308** [comment]
ok what do i need to do/ change?

**Comment by KimieStar** [comment]
please come to our discord https://discord.gg/r2kGbn3pww and follow the tutorial to correctly test the game

**Comment by XoX02308** [comment]
where can i find it in the discord server i'm not finding it. Also for /verify, i have searched the server 20 times and have not found where the 2 numbers are

**Comment by red-prig** [comment]
@XoX02308 In order to find the codes, it is enough to read #faq and #rules, well, if you can't read or don't want to get acquainted with the rules of the server, well, this is your ceiling.

**Comment by XoX02308** [comment]
I have read it a billion times where and how can i see the f numbers

**Comment by red-prig** [comment]
@XoX02308 Nowhere is it written that these are numbers, omg

**Comment by XoX02308** [comment]
then what do i need to type
