### ISSUE TITLE
Gran Tourismo 7

### ISSUE THREAD

**Issue by XoX02308** [red-prig/fpps4-game-compatibility#1638]
### Game Name

Gran Tourismo 7

### Game code

CUSA24769

### Game version

V01.00

### Used emulator's version

1.2.1

### Current status

Nothing

### Error

access violation (216)
![image](https://github.com/red-prig/fpps4-game-compatibility/assets/138152351/4a5b4a19-6300-46b0-9b01-3258c2d5323d)

### Description

access violation (216) 

Hacks change nothing

### Used hacks

MEMORY_BOUND_HACK

**Comment by red-prig** [comment]
duplicate https://github.com/red-prig/fpps4-game-compatibility/issues/196
