### ISSUE TITLE
Coffee Talk - CUSA16315

### ISSUE THREAD

**Issue by Sadamekaze** [red-prig/fpps4-game-compatibility#1663]
### Game Name

Coffee Talk

### Game code

CUSA16315

### Game version

01.00

### Used emulator's version

https://github.com/red-prig/fpPS4/commit/d6eef26c8552e05515e1c16ce28fd9790cf2fe87

### Current status

Boots

### Error

Crash after load mp4

### Description

After select language after that emulator loading mp4 crashes

### Screenshots

![image](https://github.com/red-prig/fpps4-game-compatibility/assets/50436943/6b634f91-47ad-4b98-b480-b92ce52487ba)
![image](https://github.com/red-prig/fpps4-game-compatibility/assets/50436943/978e3298-d223-4cdc-b8d0-e913ff4e667b)
![image](https://github.com/red-prig/fpps4-game-compatibility/assets/50436943/d952fdb2-fac2-4200-a037-315dd76a36ee)
![image](https://github.com/red-prig/fpps4-game-compatibility/assets/50436943/250d9434-d967-4abf-b8fe-116e17317188)

### Log File

[log.txt](https://github.com/red-prig/fpps4-game-compatibility/files/12062618/log.txt)

**Comment by red-prig** [comment]
duplicate https://github.com/red-prig/fpps4-game-compatibility/issues/260
