### ISSUE TITLE
Error  Ghost of Tsushima

### ISSUE THREAD

**Issue by alpahroket** [red-prig/fpps4-game-compatibility#1681]
### Game Name

Ghost of Tsushima

### Game code

CUSA11456

### Game version

02.18

### Used emulator's version

01

### Current status

Playable

### Error

ERROR - Unable to start main application
ENOTDIR: Not a directory scandir 'E:/Launcher/Gmaes/++build-r-retail 0401.1715 us-patch ship p218rc1 ++ /

### Description

Dont have a description

### Screenshots

![image](https://github.com/red-prig/fpps4-game-compatibility/assets/48603620/f197a17b-d950-4e41-8d4d-08718b6053f9)

**Comment by red-prig** [comment]
Firstly, your error has nothing to do with the emulator (you configured the graphical interface incorrectly, and secondly, a duplicate)

**Comment by alpahroket** [comment]
> Firstly, your error has nothing to do with the emulator (you configured the graphical interface incorrectly, and secondly, a duplicate)
How i configure conrretly the graphique interface ?

**Comment by alpahroket** [comment]
ok i resolve the problem
