### ISSUE TITLE
BloodBorne

### ISSUE THREAD

**Issue by Ktylllxy** [red-prig/fpps4-game-compatibility#1692]
### Game Name

BloodBorne

### Game code

CUSA03173

### Game version

01.09

### Used emulator's version

1.2.1

### Current status

not playable

### Error

nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue   

...

Warn, file libSceAvPlayer.prx not loaded!                                                                               Warn, file libSceVideoRecording.prx not loaded!                                                                         Warn, file libSceGameLiveStreaming.prx not loaded!                                                                      Warn, file libSceWebBrowserDialog.prx not loaded!                                                                       Warn, file libSceNpAuth.prx not loaded!                                                                                 Warn, file libSceNpUtility.prx not loaded!                                                                              Warn, file libSceSsl.prx not loaded!                                                                                    Redirected:DAC5B3858A851F81:_Stdout                                                                                     Redirected:3148C2E256C7ACAE:fflush                                                                                      Redirected:9FB01EA70474B37E:mktime                                                                                      Redirected:C0B9459301BD51C4:time                                                                                        Redirected:79F84AFD84946184:localtime                                                                                   Redirected:D6679C3FB4602360:gmtime                                                                                      Redirected:E5B05A7062F22CEB:gmtime_s   

### Description

don't work

### Used hacks

all

### Screenshots

![изображение](https://github.com/red-prig/fpps4-game-compatibility/assets/44523028/951c2096-aea2-4652-b0bb-7839511ced83)

### Log File

[cmd-backup.txt](https://github.com/red-prig/fpps4-game-compatibility/files/12585992/cmd-backup.txt)

**Comment by KimieStar** [comment]
duplicate @gandalfthewhite19890404 close
