### ISSUE TITLE
God of war ragnarok

### ISSUE THREAD

**Issue by Nickihaha** [red-prig/fpps4-game-compatibility#1710]
### Game Name

God of war ragnarok

### Game code

idk

### Game version

4.02

### Used emulator's version

1.2.0

### Current status

Boots

### Error

just dosnt boot

### Description

just stays in the boot menu

**Comment by MrSn0wy** [comment]
Heya, next time please look if someone else already made an issue regarding this game (hint: someone already has). Also when something doesn't start the status isn't "boots" but it's "nothing", also the game code is not valid, in TL you can see the code when you click on a game.
