### ISSUE TITLE
Horizon Forbidden West game doesn't launch

### ISSUE THREAD

**Issue by AnonimiSuS02** [red-prig/fpps4-game-compatibility#1722]
### Game Name

Horizon Forbidden West

### Game code

cusa24705

### Game version

1.0.4

### Used emulator's version

1.2.3

### Current status

Nothing

### Error

sceAppContentInitialize
[main:21416] nop nid:libSceNpEntitlementAccess:8CEF0333CA327A0A:sceNpEntitlementAccessInitialize

### Description

I don't know what it means so i just ask for help. (game doesn't start)

### Screenshots

![Screenshot 2023-11-22 133413](https://github.com/red-prig/fpps4-game-compatibility/assets/151751651/a4f03519-1f74-49ac-9594-be8b7ffcc14e)

**Comment by red-prig** [comment]
duplicate
