### ISSUE TITLE
Santa's Xmas Adventure CUSA25445

### ISSUE THREAD

**Issue by yaya54840** [red-prig/fpps4-game-compatibility#1737]
### Game Name

Santa's Xmas Adventure

### Game code

CUSA25455

### Game version

1.02

### Used emulator's version

000305d

### Current status

Playable

### Error

No error

### Description

No hacks
This game can be played at 15 fps
The audio is decent, but I'll leave it off in the game option

### Screenshots

![Capture d'écran_20231205_170631](https://github.com/red-prig/fpps4-game-compatibility/assets/47884186/bc568ffe-f189-435f-893a-efde14cb2f55)
![Capture d'écran_20231205_170717](https://github.com/red-prig/fpps4-game-compatibility/assets/47884186/0b3bbfb4-c43c-483a-a604-0f80786e0cc5)

### Log File

[log.txt](https://github.com/red-prig/fpps4-game-compatibility/files/13562640/log.txt)

**Comment by red-prig** [comment]
[duplicate](https://github.com/red-prig/fpps4-game-compatibility/labels/duplicate)

**Comment by yaya54840** [comment]
Oh sorry 
red-prig delete duplicate
