### ISSUE TITLE
Five Nights at Freddy's Security Breach - CUSA24172

### ISSUE THREAD

**Issue by Ordinary205** [red-prig/fpps4-game-compatibility#1746]
### Game Name

Five Nights at Freddy's Security Breach

### Game code

CUSA24172

### Game version

1.00

### Used emulator's version

000305d

### Current status

Nothing

### Error

[main:13068] nop nid:libkernel:A8249FA8320B967B:sceKernelMemoryPoolExpand

### Description

No sign of boot.

### Screenshots

![FNAF Security Breach](https://github.com/red-prig/fpps4-game-compatibility/assets/125112932/a3acd6aa-cac7-4134-b476-8c6ff3be7e46)
![FNAF Security Breach console](https://github.com/red-prig/fpps4-game-compatibility/assets/125112932/52ed4919-b09d-462c-853d-7f150552ba52)

**Comment by red-prig** [comment]
https://github.com/red-prig/fpps4-game-compatibility/issues/325
