### ISSUE TITLE
Death's Gambit - CUSA05987

### ISSUE THREAD

**Issue by yaya54840** [red-prig/fpps4-game-compatibility#1832]
### Game Name

Death's Gambit

### Game code

CUSA05987

### Game version

1.08

### Used emulator's version

585d06f

### Current status

Menus

### Error

No

### Description

Audio good
Good menu display
after launch to play
  Audio menus ok
but black screen

### Used hacks

IMAGE_LOAD_HACK

### Screenshots

![Capture d'écran_20240131_101918](https://github.com/red-prig/fpps4-game-compatibility/assets/47884186/ff485be4-9537-44a3-ad07-a60ae0d45b72)
![Capture d'écran_20240131_101929](https://github.com/red-prig/fpps4-game-compatibility/assets/47884186/edcb9b49-d813-467f-b023-dc39a46d791e)
![Capture d'écran_20240131_101733](https://github.com/red-prig/fpps4-game-compatibility/assets/47884186/a2e7a50d-91b4-404f-a3c7-ca1fb8590630)
![Capture d'écran_20240131_102005](https://github.com/red-prig/fpps4-game-compatibility/assets/47884186/8af89dcb-423b-46e3-a795-9b72dec89a1a)
![Capture d'écran_20240131_102041](https://github.com/red-prig/fpps4-game-compatibility/assets/47884186/358737c6-b15b-4a0d-9f66-4677ec5881a3)

### Log File

[log.txt](https://github.com/red-prig/fpps4-game-compatibility/files/14109785/log.txt)

**Comment by red-prig** [comment]
dublicate

**Comment by yaya54840** [comment]
Sorry Red prig
I didn't find it in the search
