### ISSUE TITLE
Red Dead Redemption

### ISSUE THREAD

**Issue by WNTRFIL** [red-prig/fpps4-game-compatibility#1833]
### Game Name

Red Dead Redemption

### Game code

CUSA36843

### Game version

1.03

### Used emulator's version

9b941dc

### Current status

Playable

### Error

An unhandled exception occurred at $000000010006AB37:
EAssertionFailed: SCE_AUDIO_OUT_PARAM_FORMAT_S16_8CH (ps4_libsceaudioout.pas, line 671)

### Description

Crash

### Used hacks

MEMORY_BOUND_HACK

### Screenshots

No response

### Log File

No response

**Comment by WNTRFIL** [comment]
No response

**Comment by WNTRFIL** [comment]
No response

**Comment by yaya54840** [comment]
Hi Gandalfwithe
????!!
