### ISSUE TITLE
Slain - CUSA06465

### ISSUE THREAD

**Issue by Hermiten** [red-prig/fpps4-game-compatibility#1839]
### Game Name

Slain

### Game code

06465

### Game version

1.0

### Used emulator's version

2d97b84

### Current status

Boots

### Error

No error

### Description

We can hear the sound but weird
Black screen, 8 FPS I think it can go further if I wait 1h

### Used hacks

COMPUTE_DISABLE_HACK

**Comment by gandalfthewhite19890404** [comment]
Closed as duplicate
