### ISSUE TITLE
Blasphemous - CUSA16275

### ISSUE THREAD

**Issue by Digote** [red-prig/fpps4-game-compatibility#1947]
### Game Name

Blasphemous

### Game code

CUSA16275

### Game version

1.0.0

### Used emulator's version

ad0b024

### Current status

Nothing

### Error

vkQueueSubmit:VK_ERROR_DEVICE_LOST

### Description

Nothing

**Comment by gandalfthewhite19890404** [comment]
Closed as duplicate
