### ISSUE TITLE
DmC Devil May Cry™: Definitive Edition - CUSA01022

### ISSUE THREAD

**Issue by konaherson** [red-prig/fpps4-game-compatibility#1979]
### Game Name

DmC Devil May Cry Definitive Edition v1.03

### Game code

CUSA01022

### Game version

1.00

### Used emulator's version

red-prig/fpPS4@ae44cd4

### Current status

Nothing

### Error

 Unable to find the compatibility status for "DmC Devil May Cry™: Definitive Edition" (CUSA01022) on the fpPS4 game database!

### Description

no

### Screenshots

no

### Log File

no

**Comment by red-prig** [comment]
There is no objective data from testing the game so I am closing the issue
