### ISSUE TITLE
JoJo's Bizarre Adventure: All-Star Battle R - CUSA28972

### ISSUE THREAD

**Issue by Axekinn** [red-prig/fpps4-game-compatibility#2025]
### Game Name

JoJo's Bizarre Adventure: All-Star Battle R

### Game code

CUSA28972

### Game version

1.0

### Used emulator's version

red-prig/fpPS4@ad0b024

### Current status

Nothing

### Error

nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue

### Description

crash

### Screenshots

![image](https://github.com/red-prig/fpps4-game-compatibility/assets/57594354/f7181c2f-0393-44bb-a1d8-4fb0c23c2b1e)

### Log File

[logs.txt](https://github.com/user-attachments/files/15837745/logs.txt)

**Comment by gandalfthewhite19890404** [comment]
closed as duplicate
