### ISSUE TITLE
Guilty Gear Xrd Revelator #CUSA04112

### ISSUE THREAD

**Issue by Rogerhithub** [red-prig/fpps4-game-compatibility#2203]
### Game Name

Guilty Gear Xrd Revelator

### Game code

CUSA04112

### Game version

01.00

### Used emulator's version

1.2.4

### Current status

Nothing

### Error

LibSceJson2

### Description

![Uploading Screenshot 2024-09-06 170531.png…]()

### Screenshots

![Screenshot 2024-09-06 170531](https://github.com/user-attachments/assets/dad2b0d1-6fd3-4318-a3dc-b1d54de49836)

**Comment by gandalfthewhite19890404** [comment]
Add whitelisted libs

**Comment by red-prig** [comment]
duplicate
