### ISSUE TITLE
jogo hollow knigth

### ISSUE THREAD

**Issue by ashcampeao** [red-prig/fpps4-game-compatibility#2209]
### Game Name

hollow knigth

### Game code

CUSA13285

### Game version

01.00

### Used emulator's version

Fpps4

### Current status

Ingame

### Error

goes up to 14fps
### Description

![image](https://github.com/user-attachments/assets/fe1713b5-d2ce-484a-b42e-7f0634d2d589)

### Used hacks

DEPTH_DISABLE_HACK, COMPUTE_DISABLE_HACK, MEMORY_BOUND_HACK, IMAGE_LOAD_HACK, DISABLE_SRGB_HACK

### Screenshots

![image](https://github.com/user-attachments/assets/4ff4c100-97fc-4245-8fca-b91b9a05f970)

### Log File

align:0000010000 mType:WC_GARLIC
[TTY]:[allocateMemoryLayout] Could not allocate direct Memory
Message: Access violation (216)
  $0000000800B5DF76 offset $00B5DF76 eboot.bin:dtInit+$00B5DF56
  $0000000800B78E5F offset $00B78E5F eboot.bin:dtInit+$00B78E3F
  $0000000800B79C83 offset $00B79C83 eboot.bin:dtInit+$00B79C63
  $0000000800B79F33 offset $00B79F33 eboot.bin:dtInit+$00B79F13
  $0000000800B7A109 offset $00B7A109 eboot.bin:dtInit+$00B7A0E9
  $0000000800CC2C0F offset $00CC2C0F eboot.bin:Entry+$0000003F
  $0000000000000001 fpPS4.exe
XInput quit!
An unhandled exception occurred at $00000001001A0C48:
EAccessViolation: Access violation
  $00000001001A0C48
  $00000001001933DC
  $00000001001932DF
  $00000001001A087A
  $00000001001A2151
  $000000010018310E
  $000000010006E35C
  $0000000100004891
  $0000000100005176
  $0000000100017F10
  $0000000100003340
  $00007FFDF2EC257D
  $00007FFDF436AF28

**Comment by gandalfthewhite19890404** [comment]
And where is screenshots?

**Comment by red-prig** [comment]
duplicate
