### ISSUE TITLE
Angry Video Game Nerd I & II Deluxe - CUSA24806

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [red-prig/fpps4-game-compatibility#221]
### **Game name**
Angry Video Game Nerd I & II Deluxe

### **Code**
CUSA24806

### **Used emulator's version**
https://github.com/red-prig/fpPS4/commit/889956cfff9807dd7c8d89437a9ce7fd2891454f

### **Current status**
Nothing.

### **Error**

```
```

### **Description**
Nothing, just white screen, fps counter is missing.

### **Screenshots:**
![image](https://user-images.githubusercontent.com/24764335/204785364-a4e8adf3-5784-483e-a07d-0d37c701ce32.png)

**Comment by and468860** [comment]
you can close page https://github.com/red-prig/fpps4-game-compatibility/issues/221 already repeated

**Comment by gandalfthewhite19890404** [comment]
Oh, sorry
