### ISSUE TITLE
Crash team racing nitro - fueled error from fpPS4

### ISSUE THREAD

**Issue by Morok999** [red-prig/fpps4-game-compatibility#2224]
### Game Name

Crash team racing nitro - fueled

### Game code

CUSA14876

### Game version

1.0.1

### Used emulator's version

1.2.4

### Current status

Playable

### Error

[main:2196] nop nid:libSceJson2:FE125171EF309F55:_ZN3sce4Json12MemAllocatorC2Ev

### Description

I spent the whole day installing the game. I read your answers to a similar error, but wherever I install libSceJson2, be it sce-module in the game folder or in the Emu folder, everything is even. HELP! Maybe I installed the wrong file or installed it in the wrong place, please tell me and give the relevant links if necessary. P.S: I know Russian

### Screenshots

![Снимок экрана 2024-10-16 154351](https://github.com/user-attachments/assets/2d2bd400-a3d4-47f3-9697-a9f139a376be)

**Comment by red-prig** [comment]
dublicate https://github.com/red-prig/fpps4-game-compatibility/issues/364
Let me remind you that this is not a support chat, these are reports on the state of the game
