### ISSUE TITLE
fifa

### ISSUE THREAD

**Issue by orlando4992** [red-prig/fpps4-game-compatibility#2225]
### Game Name

FIFA 23

### Game code

CUSA31874

### Game version

1.00

### Used emulator's version

1.2.4

### Current status

Nothing

### Error

[main:856] nop nid:libkernel:BD853C3FD4DDD99A:sceKernelAioInitializeImpl

### Description

Hi, I downloaded FIFA 23 but i have an error. You can see what is going on on the picture.

**Comment by gandalfthewhite19890404** [comment]
Don't be so stupid:
1. Search for already existed issue
2. Name it correctly
