### ISSUE TITLE
Forager - CUSA13959

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [red-prig/fpps4-game-compatibility#227]
### **Game name**
Forager

### **Code**
CUSA13959

### **Used emulator's version**
https://github.com/red-prig/fpPS4/commit/f6e2a7ee6cd72cc850ac80bf52155f5ea66ec538

### **Current status**
Playable.

### **Error**

```
```

### **Description**
Playable, had to use hacks to get good FPS, sound is working.

### **Used hacks:**
-h DEPTH_DISABLE_HACK -h COMPUTE_DISABLE_HACK -h IMAGE_TEST_HACK -h IMAGE_LOAD_HACK

### **Screenshots:**
![image](https://user-images.githubusercontent.com/24764335/204995149-394cd5c6-dba4-4b30-8786-a87043dba43f.png)

**Comment by gandalfthewhite19890404** [comment]
Closed as duplicate

**Comment by GamingDuckingalt** [comment]
remove the labels since the issue is a duplicate
