### ISSUE TITLE
Borderlands Game of The Year Edition - CUSA10455

### ISSUE THREAD

**Issue by Boiiiiiiiiiiiiiiiiiiii** [red-prig/fpps4-game-compatibility#255]
Status: Nothing

Error: nop nid:libkernel:81E0DAAA01FD9538:scePthreadKeyCreate

**Comment by gandalfthewhite19890404** [comment]
Retest, as https://github.com/red-prig/fpPS4/commit/56f0d24fcc87871fba402d9267adc3a6f472eacc was committed

**Comment by Boiiiiiiiiiiiiiiiiiiii** [comment]
new error: nop nid:libSceJson2:FE125171EF309F55:_ZN3sce4Json12MemAllocatorC2Ev

**Comment by gs-soda** [comment]
After adding libSceJson2.prx there's a new error:


``nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue
``
