### ISSUE TITLE
The Binding of Isaac: Rebirth - CUSA01344

### ISSUE THREAD

**Issue by Boiiiiiiiiiiiiiiiiiiii** [red-prig/fpps4-game-compatibility#279]
Status: Nothing 

Error: An unhandled exception occurred at $000000010006FD54:
EAssertionFailed: TODO CCB (ps4_videodrv.pas, line 2530)
  $000000010006FD54

**Comment by gandalfthewhite19890404** [comment]
Closed as duplicate
