### ISSUE TITLE
LittleBigPlanet 3 Kiosk Demo - CUSA00063

### ISSUE THREAD

**Issue by Squidtito** [red-prig/fpps4-game-compatibility#355]
status: nothing

Error: nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue

**Comment by HidekoHaruna** [comment]
All I managed to get (when trying to boot the full game, not a demo) is a white screen with 0 fps and the same error as mentioned above: _nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue_
![2023-03-21 19-53](https://user-images.githubusercontent.com/50747725/226712802-7fcf433b-e884-4558-b6f4-5906102b101b.jpg)

**Comment by Kimieggie** [comment]
> All I managed to get (when trying to boot the full game, not a demo) is a white screen with 0 fps and the same error as mentioned above: _nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue_ ![2023-03-21 19-53](https://user-images.githubusercontent.com/50747725/226712802-7fcf433b-e884-4558-b6f4-5906102b101b.jpg)

Don't post invalid reports like this.

**Comment by HidekoHaruna** [comment]
> > All I managed to get (when trying to boot the full game, not a demo) is a white screen with 0 fps and the same error as mentioned above: _nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue_ ![2023-03-21 19-53](https://user-images.githubusercontent.com/50747725/226712802-7fcf433b-e884-4558-b6f4-5906102b101b.jpg)
> 
> As well as you are posting information about a separate game you are saying full game but this issue is not for that

1. I didn't know it's required to follow the format when commenting. I thought it's required only when making a new post. Also, how can I be more informative about this when I have already provided a screenshot containing the logs, the error itself, the game version, the emulator version, and my GPU?
2. I'm talking about CUSA00063. This post is about CUSA00063. I don't even know why the post title says "kiosk demo", my game has the title ID "CUSA00063" and it's an EU retail copy.

**Comment by Kimieggie** [comment]
> > > All I managed to get (when trying to boot the full game, not a demo) is a white screen with 0 fps and the same error as mentioned above: _nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue_ ![2023-03-21 19-53](https://user-images.githubusercontent.com/50747725/226712802-7fcf433b-e884-4558-b6f4-5906102b101b.jpg)
> > 
> > As well as you are posting information about a separate game you are saying full game but this issue is not for that
> 
> 1. I didn't know it's required to follow the format when commenting. I thought it's required only when making a new post. Also, how can I be more informative about this when I have already provided a screenshot containing the logs, the error itself, the game version, the emulator version, and my GPU?
> 2. I'm talking about CUSA00063. This post is about CUSA00063. I don't even know why the post title says "kiosk demo", my game has the title ID "CUSA00063" and it's an EU retail copy.

You are literally not providing the most important information which is the emator version. You can't expect people to read the version off of screenshot. Just input itike you do when you create an issue. Also your are just commenting on the wrong issue there is a separate one with the same cusa that is not the demo next time look before posting. And as a last thing while formatting is not mandatory you'll just make it easier for the devs and other testers if u take a minute to copy paste the format but you do you.

**Comment by Kimieggie** [comment]
@HidekoHaruna Additionally you are using an old version of the emu. For testing you should always use the latest trunk action. If u want an easier way to set up and update or just in general for questions please do join the [discord server](https://discord.gg/up9qatpX7M) you can check out the tutorials there.

**Comment by HidekoHaruna** [comment]
> @HidekoHaruna Additionally you are using an old version of the emu. For testing you should always use the latest trunk action. If u want an easier way to set up and update or just in general for questions please do join the [discord server](https://discord.gg/up9qatpX7M) you can check out the tutorials there.

0.0.1 is the latest version.

**Comment by GamingDuckingalt** [comment]
go to actions and use the latest version of the trunk since the version you are using is old now.

**Comment by Kimieggie** [comment]
@HidekoHaruna no 0.0.1 is not the latest version. Go to the discord I linked you and check out the tutorials
