### ISSUE TITLE
Five Nights At Freddy's - CUSA16870

### ISSUE THREAD

**Issue by Squidtito** [red-prig/fpps4-game-compatibility#358]
Status: Nothing

nop nid:libSceNgs2:98F620538A18A6E6:sceNgs2SystemCreateWithAllocator

**Comment by gandalfthewhite19890404** [comment]
Take libSceNgs2.prx and put to sce_module folder, please, and retest

**Comment by and468860** [comment]
close the page already repeat

**Comment by GamingDuckingalt** [comment]
remove the labels if it's a duplicate
