### ISSUE TITLE
Wizard of Legended  CUSA10927 

### ISSUE THREAD

**Issue by and468860** [red-prig/fpps4-game-compatibility#362]
![Gravar_2022_12_06_10_00_16_736 mp4_snapshot_00 14 332](https://user-images.githubusercontent.com/61087055/205879993-6cf6b940-742d-4114-84a6-0d74a3a5de75.jpg)
Message: Access violation (216)
  $0000000800F5323F offset $00F5323F eboot.bin:Entry+$00F531BF
  $0000000800F53173 offset $00F53173 eboot.bin:Entry+$00F530F3
  $000000000DD7D820 offset $0007D820 Il2CppUserAssemblies.prx:il2cpp_api_lookup_symbol+$00002990
  $000000080051E8E8 offset $0051E8E8 eboot.bin:Entry+$0051E868
  $000000080092092F offset $0092092F eboot.bin:Entry+$009208AF
  $000000080051E5ED offset $0051E5ED eboot.bin:Entry+$0051E56D
  $0000000800973072 offset $00973072 eboot.bin:Entry+$00972FF2
  $000000000E25CB14 offset $0055CB14 Il2CppUserAssemblies.prx:unity_mono_set_user_malloc_mutex+$004C4884
  $000000000E598FF1 offset $00898FF1 Il2CppUserAssemblies.prx:unity_mono_set_user_malloc_mutex+$00800D61
  $000000000E599718 offset $00899718 Il2CppUserAssemblies.prx:unity_mono_set_user_malloc_mutex+$00801488
  $000000000E6C3408 offset $009C3408 Il2CppUserAssemblies.prx:unity_mono_set_user_malloc_mutex+$0092B178
  $0000000008C1208A offset $0002208A libc.prx:free+$0000000A
  $0000000800F6ADA1 offset $00F6ADA1 eboot.bin:Entry+$00F6AD21
  $0000000800F3A8D4 offset $00F3A8D4 eboot.bin:Entry+$00F3A854
  $0000000800F378CF offset $00F378CF eboot.bin:Entry+$00F3784F
  $000000000DFFFC4F offset $002FFC4F Il2CppUserAssemblies.prx:unity_mono_set_user_malloc_mutex+$002679BF
  $0000000800F40BC3 offset $00F40BC3 eboot.bin:Entry+$00F40B43
  $00000008008471E5 offset $008471E5 eboot.bin:Entry+$00847165
  $00000001000419F6 fpPS4.exe
[TWin32WidgetSet.Destroy] WARNING: There are 1 TimerInfo structures left, I'll free them
  $000000000DD5BA17 offset $0005BA17 Il2CppUserAssemblies.prx:WriteZStream+$0005A6B7
  $000000080091235E offset $0091235E eboot.bin:Entry+$009122DE

**Comment by gandalfthewhite19890404** [comment]
Retest, as https://github.com/red-prig/fpPS4/commit/df6317ba0981983b2f9941034993ecbbe394c4bf was committed

**Comment by gandalfthewhite19890404** [comment]
### **Status:**
Menus

### **Error:**
```
An unhandled exception occurred at $0000000100109CE0:
EAssertionFailed: sparse not support for host (vHostBufferManager.pas, line 263)
  $0000000100109CE0
  $0000000100072143
  $0000000100075530
  $00000001000716B4
  $0000000100005076
  $0000000100014371
  $00007FFE5A0274B4
  $00007FFE5BEC26A1

[TWin32WidgetSet.Destroy] WARNING: There are 1 TimerInfo structures left, I'll free them
An unhandled exception occurred at $000000010020CE9D:
EAccessViolation: Access violation
```

### **Screenshots:**
![image](https://user-images.githubusercontent.com/24764335/208247167-dbafb5b8-cf24-4d2f-b58e-c2c38b530643.png)
