### ISSUE TITLE
PSX-FPKG 

### ISSUE THREAD

**Issue by and468860** [red-prig/fpps4-game-compatibility#381]
nop nid:libkernel:FD6E3123969523CC:sceKernelSetProcessProperty

**Comment by and468860** [comment]
EAssertionFailed: MIMG?14 (emit_mimg.pas, line 1037)

**Comment by and468860** [comment]
EAssertionFailed: MIMG?14 (emit_mimg.pas, line 1037)

**Comment by gandalfthewhite19890404** [comment]
retest

**Comment by gandalfthewhite19890404** [comment]
What is that app? I will close it if no response in a week.

**Comment by gandalfthewhite19890404** [comment]
Closed as non-responded and obsolete
