### ISSUE TITLE
Penguin Wars CUSA11292

### ISSUE THREAD

**Issue by and468860** [red-prig/fpps4-game-compatibility#389]
$0000000008E31264 offset $00021264 libc.prx:abort+$00000004
  $00000008010D5791 offset $010D5791 eboot.bin:Entry+$010D5711
  $0000000008E3208A offset $0002208A libc.prx:free+$0000000A
  $000000000D8DA008 offset $0006A008 mono-ps4.prx:mono_method_get_flags+$00019AB8
  $000000000D930369 offset $000C0369 mono-ps4.prx:mono_aot_get_method+$00001749
  $000000000D95BB05 offset $000EBB05 mono-ps4.prx:Unknow+$00005175
  $0000000010E974FD offset $005174FD MonoAssembliesPS4.prx:dtInit+$005174FD
  $0000000010F200A9 offset $005A00A9 MonoAssembliesPS4.prx:dtInit+$005A00A9
  $000000000D962A04 offset $000F2A04 mono-ps4.prx:mono_get_runtime_build_info+$00000AA4
  $000000000D8EF00E offset $0007F00E mono-ps4.prx:mono_runtime_invoke+$0000006E
  $00000008009C5C10 offset $009C5C10 eboot.bin:Entry+$009C5B90
  $00000008009C7E67 offset $009C7E67 eboot.bin:Entry+$009C7DE7
  $00000008006CF3B2 offset $006CF3B2 eboot.bin:Entry+$006CF332
  $00000008010CF4BD offset $010CF4BD eboot.bin:Entry+$010CF43D
  $00000008010D4241 offset $010D4241 eboot.bin:Entry+$010D41C1
  $00000008000000BF offset $000000BF eboot.bin:Entry+$0000003F
  $0000000000000001 fpPS4.exe

**Comment by gandalfthewhite19890404** [comment]
Already exist.
