### ISSUE TITLE
Turok - CUSA20201

### ISSUE THREAD

**Issue by LukeWarnut** [red-prig/fpps4-game-compatibility#431]
### Code:
CUSA20201

### Emulator version:
https://github.com/red-prig/fpPS4/commit/5ee6d51eada3c2099ac1d3952463d2c0be1d47be

### Status:
Boots

### Description:
Boots with a black screen, then halts after nopping a service.

### Error:

```
nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue
```

### Log:
[log-turok.txt](https://github.com/red-prig/fpps4-game-compatibility/files/10188509/log-turok.txt)

**Comment by and468860** [comment]
repeated page

**Comment by GAMERRPCS3** [comment]
Retest

Used emulator's version - 110109b

![2](https://user-images.githubusercontent.com/121258975/232259076-9ac35ca5-dcec-4f2d-9bed-47a3fce6fae7.png)
![3](https://user-images.githubusercontent.com/121258975/232259080-bb8243ab-5c93-4642-ac6b-ce96843f44ab.png)

**Comment by gandalfthewhite19890404** [comment]
I can't understand - why sceGnmMapComputeQueue is not triggering?

**Comment by GamingDuckingalt** [comment]
Retest

**Comment by GAMERRPCS3** [comment]
Retest

Used emulator's version - c2a4265

COMPUTE_DISABLE_HACK
