### ISSUE TITLE
Chip and Dale Remastered

### ISSUE THREAD

**Issue by DiegoTegani** [red-prig/fpps4-game-compatibility#432]
### **Game name**

Chip and Dale Remastered

**CODE**

CDRR00001

**Version**

 v1.00

**Used Emulator's version**

red-prig/fpPS4@5ee6d51

**Hacks**

it is not necessary.

**Current satus**

playable

**Description**

It is working, but the FPS is between 3 and 4. The sound is correct.

**Log file**

[log.txt](https://github.com/red-prig/fpps4-game-compatibility/files/10188618/log.txt)

**Screenshots**

![1](https://user-images.githubusercontent.com/45742711/206542100-c50912a4-580d-4bf4-adee-6eade7515efd.png)

![2](https://user-images.githubusercontent.com/45742711/206542402-fa87ad5d-0499-4be7-822d-b0de18d7ec5c.png)

**Comment by red-prig** [comment]
that dublicate? (https://github.com/red-prig/fpps4-game-compatibility/issues/72)

**Comment by DiegoTegani** [comment]
I'm sorry, I thought that in my search I hadn't found the game, it should have some filter, you can close it.
