### ISSUE TITLE
Among Us - CUSA27793

### ISSUE THREAD

**Issue by Squidtito** [red-prig/fpps4-game-compatibility#435]
status: Nothing

nop nid:libSceSsl:4C37D0A8EFE031B6:sceSslGetCaCerts

**Comment by Boiiiiiiiiiiiiiiiiiiii** [comment]
duplicate, delete please

**Comment by Squidtito** [comment]
This is a retest, is there supposed to be a different way of doing that?

**Comment by gandalfthewhite19890404** [comment]
> This is a retest, is there supposed to be a different way of doing that?

Find existing issue and reply in it.
