### ISSUE TITLE
Ghost of Tsushima: Director's Cut - CUSA13323

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [red-prig/fpps4-game-compatibility#440]
### **Game name**
Ghost of Tsushima: Director's Cut

### **Code**
CUSA13323

### **Used emulator's version**
https://github.com/red-prig/fpPS4/commit/5725cef328c097a396d280261a85744879d8724d

### **Current status:**
Nothing

### **Error:**
```
nop nid:libkernel:D92284C7A6D2ABFE:sceKernelBatchMap
```

**Comment by GamingDuckingalt** [comment]
Retest

**Comment by GamingDuckingalt** [comment]
please retest since SceKernalBatchMap is added.

**Comment by gandalfthewhite19890404** [comment]
Tested with https://github.com/red-prig/fpPS4/commit/5fa656dee2e37c828ec13a2cad5e4e82a6f8a127
nop nid:libSceNet:F6F036696F821EE0:sceNetInetNtop

**Comment by gandalfthewhite19890404** [comment]
Retest

**Comment by gandalfthewhite19890404** [comment]
nop nid:libSceNet:F6F036696F821EE0:sceNetInetNtop

**Comment by GamingDuckingalt** [comment]
Retest

**Comment by gandalfthewhite19890404** [comment]
nop nid:libSceOpenPsId:0CB39172BA14A9B7:sceKernelGetOpenPsId

**Comment by gandalfthewhite19890404** [comment]
Also game needs this:
nop nid:libSceShareUtility:8FB0E56A50731E1F:sceShareUtilityInitializeEx2
nop nid:libSceShareUtility:BB86C21A4AA1381E:sceShareUtilityAdvanceInitialize
nop nid:libSceShareUtility:91AAE72616A474A8:sceShareUtilityAdvanceSetUploadContentData
nop nid:libSceGnmDriver:03EB86ABEDCA16D4:sceGnmMapComputeQueueWithPriority
nop nid:libSceGnmDriver:7DFACD40EB21A30B:sceGnmComputeWaitOnAddress
nop nid:libSceGnmDriver:5E2CB3359F49E274:sceGnmSetWaveLimitMultipliers
nop nid:libSceGnmDriver:6D7E486D1BC40979:sceGnmDingDong

**Comment by Addy2004** [comment]
> nop nid:libSceGnmDriver:6D7E486D1BC40979:sceGnmDingDong
GnmDingDong my favorite function

**Comment by gandalfthewhite19890404** [comment]
Retest

**Comment by gandalfthewhite19890404** [comment]
[main:4392] nop nid:libSceShareUtility:8FB0E56A50731E1F:sceShareUtilityInitializeEx2

**Comment by SpurgtFuglen** [comment]
Is it possible to get it to work? 
![image](https://github.com/red-prig/fpps4-game-compatibility/assets/134840527/c3934c3a-ff7c-412d-8867-404d14e68ae0)

![image](https://github.com/red-prig/fpps4-game-compatibility/assets/134840527/d72801df-8813-4a64-b7c1-35709e618b5d)

**Comment by ArtemVideoGames** [comment]
@SpurgtFuglen please join to our Discord server by invite in https://github.com/red-prig/fpPS4
