### ISSUE TITLE
Resident Evil HD Remaster  CUSA01067

### ISSUE THREAD

**Issue by and468860** [red-prig/fpps4-game-compatibility#484]
## Error
nop nid:libSceNpManager:39A777AEF63F3494:sceNpHasSignedUp
BeginT

**Comment by gandalfthewhite19890404** [comment]
Retest

**Comment by and468860** [comment]
application all

nid:libSceNpParty:9616024D098191DB:sceNpPartyInitialize
nop nid:libSceSysUtil:12EED0341F71D6BD:sceSysUtilSendNpDebugNotificationRequest
nop nid:libkernel:5B401AF8703037A5:syscall
