### ISSUE TITLE
Horizon Chase Turbo - CUSA11452

### ISSUE THREAD

**Issue by and468860** [red-prig/fpps4-game-compatibility#530]
(vHostBufferManager.pas, line 263

**Comment by gs-soda** [comment]
Update: Game reaches title screen and crashes with nop nid:libSceHttp:A858364AEC932496:sceHttpSetAuthEnabled when trying to enter the menu.
Version: red-prig/fpPS4@c9615d8
CUSA11452

**Comment by Kalorte** [comment]
## Used emulator's version
https://github.com/red-prig/fpPS4/commit/41b20dcda94bbffe7677470d308dc39758ce5a60

## Status
None

## Error
vkQueueBindSparse:VK_ERROR_INITIALIZATION_FAILED
An unhandled exception occurred at $0000000100112180:
EAssertionFailed: create sparse buffer fail (vHostBufferManager.pas, line 263)
  $0000000100112180
  $0000000100076993
  $0000000100079E50
  $0000000100075EE4
  $0000000100005166
  $0000000100014531
  $00007FFD758D26BD
  $00007FFD7694DFB8

An unhandled exception occurred at $00000001002132DB:

**Comment by gs-soda** [comment]
Personally the game crashes with:
`nop nid:libSceHttp:CA282BE15D3F1D33:sceHttpSetRecvTimeOut`
Modules added: libSceHttp.prx
CUSA11452
red-prig/fpps4@6400cee

**Comment by GamingDuckingalt** [comment]
Retest

**Comment by gs-soda** [comment]
`nop nid:libSceHttp:CA282BE15D3F1D33:sceHttpSetRecvTimeOut` is fixed

New error: `nop nid:libSceHttp:C5E8057D9281565C:sceHttpSetSendTimeOut`

**Comment by gs-soda** [comment]
`nop nid:libSceHttp:C5E8057D9281565C:sceHttpSetSendTimeOut` is fixed
New error: `nop nid:libSceHttp:3C3C52E3CC4640BB:sceHttpSetChunkedTransferEnabled`
Game Version 2.51

Game Version 1.00 gives the following error:
An unhandled exception occurred at $000000010012C1C0:
EAssertionFailed: sparse not support for host (vHostBufferManager.pas, line 261)
  $000000010012C1C0
  $0000000100082233
  $00000001000856F0
  $0000000100081784
  $0000000100004FA6
  $0000000100014441
  $00007FFC698426BD
  $00007FFC6A98DFB8

An unhandled exception occurred at $0000000100173F74:
Press any key to continue . . .

**Comment by ArbestRi** [comment]
Retest

**Comment by gs-soda** [comment]
New error 
`Message: Access violation (216)
  $0000000009A635CD offset $000435CD libc.prx:strlen+$0000000D
[AsyncReadManager:2784] open:/archive/mount/point/Media/sharedassets3.assets.resS 0x0000 (000)
[AsyncReadManager:2784] open:/app0/Media/sharedassets3.assets.resS 0x0000 (000)
  $0000000009A5B863 offset $0003B863 libc.prx:_Mbtowc+$00000C03
  $0000000009A5B0DE offset $0003B0DE libc.prx:_Mbtowc+$0000047E
  $0000000009A4CB01 offset $0002CB01 libc.prx:snprintf_s+$000000C1
  $0000000801270694 offset $01270694 eboot.bin:sceLibSecureHashHmac+$01244CB4
  $0000000801269237 offset $01269237 eboot.bin:sceLibSecureHashHmac+$0123D857
  $0000000801269C20 offset $01269C20 eboot.bin:sceLibSecureHashHmac+$0123E240
  $00000008009680DC offset $009680DC eboot.bin:sceLibSecureHashHmac+$0093C6FC
  $00000008009684D5 offset $009684D5 eboot.bin:sceLibSecureHashHmac+$0093CAF5
  $0000000800967B4E offset $00967B4E eboot.bin:sceLibSecureHashHmac+$0093C16E
  $0000000800A268DD offset $00A268DD eboot.bin:sceLibSecureHashHmac+$009FAEFD
  $0000000100042AA6 fpPS4.exe`

**Comment by Hermiten** [comment]
Version 1.00 without hacks:

> vkQueueBindSparse:VK_ERROR_INITIALIZATION_FAILED
> An unhandled exception occurred at $000000010012E580:
> EAssertionFailed: create sparse buffer fail (vHostBufferManager.pas, line 263)
>   $000000010012E580
>   $00000001000845B3
>   $0000000100087A70
>   $0000000100083B04
>   $0000000100004FA6
>   $0000000100014441
>   $00007FFCD22B26BD
>   $00007FFCD24EDFB8

**Comment by ArbestRi** [comment]
This game is actually Nothing. The comment by @gs-soda is a complete lie. This is proof:
```
An unhandled exception occurred at $0000000100134F90:
EAssertionFailed: sparse not support for host (vHostBufferManager.pas, line 261)
  $0000000100134F90
  $000000010008BB23
  $000000010008EFE0
  $000000010008B074
  $0000000100005056
  $00000001000144F1
  $00007FFE0A2826BD
  $00007FFE0BD8DFB8

An unhandled exception occurred at $00000001002361BB:
EAccessViolation: Access violation
```

**Comment by ArbestRi** [comment]
With version 2.11, I saw something for a little bit and it crashed with:
```
Message: Access violation (216)
  $0000000009B035CD offset $000435CD libc.prx:strlen+$0000000D
  $0000000009AFB863 offset $0003B863 libc.prx:_Mbtowc+$00000C03
  $0000000009AFB0DE offset $0003B0DE libc.prx:_Mbtowc+$0000047E
  $0000000009AECB01 offset $0002CB01 libc.prx:snprintf_s+$000000C1
  $0000000801270694 offset $01270694 eboot.bin:sceLibSecureHashHmac+$01244CB4
  $0000000801269237 offset $01269237 eboot.bin:sceLibSecureHashHmac+$0123D857
  $0000000801269C20 offset $01269C20 eboot.bin:sceLibSecureHashHmac+$0123E240
  $00000008009680DC offset $009680DC eboot.bin:sceLibSecureHashHmac+$0093C6FC
  $00000008009684D5 offset $009684D5 eboot.bin:sceLibSecureHashHmac+$0093CAF5
  $0000000800967B4E offset $00967B4E eboot.bin:sceLibSecureHashHmac+$0093C16E
  $0000000800A268DD offset $00A268DD eboot.bin:sceLibSecureHashHmac+$009FAEFD
  $0000000100042B76 fpPS4.exe
An unhandled exception occurred at $00000001002361BB:
```
I can't post a screenshot because it crashes SOOOOOOOOOOOOOOOOOOOO quick.

**Comment by ArbestRi** [comment]
Got it to run further with glitchy sound. Still can't post screenshots

**Comment by ArbestRi** [comment]
![image](https://user-images.githubusercontent.com/86171223/222027043-c68b6f9d-ef56-4add-a4c6-e90d1a3efe3b.png)
Trying to load menu crashes with:
`vkQueueSubmit:VK_ERROR_DEVICE_LOST`

**Comment by not-ishak** [comment]
How to fix this : 
Error ( nop nid:libSceAvPlayer:A3D79646448BF8CE:sceAvPlayerInitEx )
