### ISSUE TITLE
Santa's Xmas Adventure - CUSA25445

### ISSUE THREAD

**Issue by JohnGodgames** [red-prig/fpps4-game-compatibility#550]
# Game name
Santa's Xmas Adventure

## Code
CUSA25445

## Used emulator's version
https://github.com/red-prig/fpPS4/commit/df6317ba0981983b2f9941034993ecbbe394c4bf

## Current status
Nothing

## Error
```
nop nid:libkernel:A8249FA8320B967B:sceKernelMemoryPoolExpand 
```

**Comment by and468860** [comment]
already repeated

**Comment by gandalfthewhite19890404** [comment]
@and468860 
your game is considered as playable, but here is an unimplemented function. Can you test and confirm playability?

**Comment by and468860** [comment]
status-playable)
![Gravar_2022_12_16_05_51_02_105 mp4_snapshot_00 06 710](https://user-images.githubusercontent.com/61087055/208031506-75a31ab0-a0fb-4d37-8841-33f1a985184e.jpg)

**Comment by gandalfthewhite19890404** [comment]
Probably with hacks - it is playable, but without - unimplemented.
I don't have this game to test. Anyway - closed as duplicate, but if something is wrong, i can reopen it at anytime,
