### ISSUE TITLE
Bloodborne - CUSA03173

### ISSUE THREAD

**Issue by Brutal-sam** [red-prig/fpps4-game-compatibility#560]
error code: nop nid:libSceNet:438A81B8DFDCD193:sceNetSocket
![FjziyZoVsAA6H6J](https://user-images.githubusercontent.com/94696121/208245505-5f866538-50f4-4600-ac96-af2143d0d878.png)

Current status: northing

**Comment by red-prig** [comment]
[duplicate](https://github.com/red-prig/fpps4-game-compatibility/labels/duplicate)
