### ISSUE TITLE
They Are Billions - CUSA20147

### ISSUE THREAD

**Issue by JohnGodgames** [red-prig/fpps4-game-compatibility#644]
# Game name
They Are Billions

## Code
CUSA20147

## Used emulator's version
https://github.com/red-prig/fpPS4/commit/a54fce10dfa7eb9b63537cdb72ea9dbe007e6e0d

## Current status
Nothing

## Error
```
nop nid:libScePosix:ED99406A411FD108:pthread_attr_setinheritsched 
```

**Comment by GamingDuckingalt** [comment]
Retest

**Comment by gandalfthewhite19890404** [comment]
nop nid:libSceAudiodec:56386C9B1A5C7B32:sceAudiodecInitLibrary

**Comment by GamingDuckingalt** [comment]
Retest
