### ISSUE TITLE
Five Nights at Freddy's - CUSA016870

### ISSUE THREAD

**Issue by gs-soda** [red-prig/fpps4-game-compatibility#729]
# Game name
Five Nights at Freddy's

## Code
CUSA16870

## Game version
1.00

## Used emulator's version
red-prig/fpPS4@bf30a29

## Current status
Nothing

## Error
```
No errors found in the log
``` 

## Description
The game closes instantly and no window shows up

## Log
[Log_Five_Nights_at_Freddy's_Fri_Dec_30_2022_18_44_11.log](https://github.com/red-prig/fpps4-game-compatibility/files/10325739/Log_Five_Nights_at_Freddy.s_Fri_Dec_30_2022_18_44_11.log)

**Comment by ArbestRi** [comment]
Duplicate

**Comment by red-prig** [comment]
duplicate
