### ISSUE TITLE
The Binding of Isaac: Rebirth - CUSA01344

### ISSUE THREAD

**Issue by gs-soda** [red-prig/fpps4-game-compatibility#802]
# Game name
The Binding of Isaac: Rebirth 

## Code
CUSA01344

## Game version
1.07

## Used emulator's version
red-prig/fpPS4@c9615d8

## Current status
Nothing

## Error
```
nop nid:libkernel:FC9A7B17EA57C4D8:pipe 
``` 

## Description
Opens a window and crashes at a white screen

**Comment by gandalfthewhite19890404** [comment]
Closed as duplicate
