### ISSUE TITLE
Almost There: The Platformer - CUSA14287

### ISSUE THREAD

**Issue by gs-soda** [red-prig/fpps4-game-compatibility#835]
# Game name
Almost There: The Platformer 

## Code
CUSA14287

## Game version
1.02

## Used emulator's version
red-prig/fpPS4@39a4e2c

## Current status
Boots

## Error
```
nop nid:libSceNpTus:D67FDD1AE9018276:sceNpTusCreateNpTitleCtxA 
``` 

## Description
Crashes at the menu

## Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/80367194/210254269-79e476c7-3edb-4c61-bc8a-cc75e5524f81.png)

**Comment by ArbestRi** [comment]
Try using hacks

**Comment by ArbestRi** [comment]
Can relate: gives error: nop nid:libSceNpTus:D67FDD1AE9018276:sceNpTusCreateNpTitleCtxA

**Comment by idk17roblox** [comment]
Duplicate of https://github.com/red-prig/fpps4-game-compatibility/issues/509
