### ISSUE TITLE
 The Art of Horizon Zero Dawn

### ISSUE THREAD

**Issue by and468860** [red-prig/fpps4-game-compatibility#849]
![The Art of Horizon Zero Dawn](https://user-images.githubusercontent.com/61087055/210369547-5fb8dd81-c7fb-40d7-9d62-04a413c4a002.jpg)

nop nid:libSceSsl:D0AD7243A2EFFD87:sceSslTerm
nop nid:libSceVideoRecording:15CF2AC652883584:sceVideoRecordingSetInfo

**Comment by gandalfthewhite19890404** [comment]
To get such screen you have to copy libSceSsl.sprx to sce_module

**Comment by ArbestRi** [comment]
Retest

**Comment by and468860** [comment]
sceVideoRecordingSetInfo  nop nid:libSceAvcap

**Comment by gandalfthewhite19890404** [comment]
What is this - sceVideoRecordingSetInfo nop nid:libSceAvcap

**Comment by GamingDuckingalt** [comment]
Retest
