### ISSUE TITLE
Dont Starve Console Edition [CUSA00327]

### ISSUE THREAD

**Issue by ransom1122** [red-prig/fpps4-game-compatibility#917]
# Game name
Dont Starve Console Edition

## Code
CUSA00327

## Game version
1.09

## Used emulator's version
red-prig/fpPS4@

## Current status
None

## Error
nop nid:libSceSaveData:4503AA0DB9376D25:sceSaveDataCheckBackupData

## Description
wont boot

## Screenshots
n/a

**Comment by gandalfthewhite19890404** [comment]
Closed as duplicate
