### ISSUE TITLE
Dont Starve Together Console Edition [CUSA04282]

### ISSUE THREAD

**Issue by ransom1122** [red-prig/fpps4-game-compatibility#918]
# Game name
Dont Starve Together Console Edition

## Code
CUSA04282

## Game version
1.26

## Used emulator's version
red-prig/fpPS4@

## Current status
None

## Error
nop nid:libSceVoice:E78A613C7D8B665B:sceVoiceStart

## Description
wont boot

## Screenshots
n/a

**Comment by gandalfthewhite19890404** [comment]
It is a duplicate.
