### ISSUE TITLE
Children of Marta - CUSA10646

### ISSUE THREAD

**Issue by Kalorte** [red-prig/fpps4-game-compatibility#940]
# Game name
Children of Marta

## Code
CUSA10646

## Game version
1.00

## Used emulator's version
https://github.com/red-prig/fpPS4/commit/a3b3bdb8f631d871985ae818d87ef074e01f97c1

## Current status
Boot

## Error
No error

## Description
Maybe playable, very long to load and play but maybe with a better computer

## Screenshots
![Capture d’écran 2023-01-04 212223](https://user-images.githubusercontent.com/151466/210644343-3e3222e3-0a14-40be-8db8-4f96423756c2.png)
![Capture d’écran 2023-01-04 212332](https://user-images.githubusercontent.com/151466/210644348-4a164c98-eeb8-4eb6-9486-c11c10cada09.png)
![Capture d’écran 2023-01-04 212853](https://user-images.githubusercontent.com/151466/210644349-4ab391e9-990b-46eb-9fd7-37743b43cb03.png)

**Comment by ArbestRi** [comment]
Consider trying hacks

**Comment by gandalfthewhite19890404** [comment]
Closed as duplicate
