### ISSUE TITLE
I Am Bread [CUSA03047]

### ISSUE THREAD

**Issue by ransom1122** [red-prig/fpps4-game-compatibility#990]
# Game name
I Am Bread

## Code
CUSA03047

## Game version
1.03

## Used emulator's version
red-prig/fpPS4@18f0dc0

## Current status
none

## Error
na

## Description
boots to a black screen

## Screenshots
![image](https://user-images.githubusercontent.com/28079950/210883864-4b00d3fa-11dd-436c-b37d-60e0e57f88ce.png)

**Comment by gandalfthewhite19890404** [comment]
Try COMPUTE_DISABLE_HACK

**Comment by gandalfthewhite19890404** [comment]
Any respond?
