### ISSUE TITLE
Kyurinagas Revenge [CUSA04413]

### ISSUE THREAD

**Issue by ransom1122** [red-prig/fpps4-game-compatibility#998]
# Game name
Kyurinagas Revenge

## Code
CUSA04413

## Game version
1.00

## Used emulator's version
red-prig/fpPS4@18f0dc0

## Current status
none

## Error
nop nid:libSceAvPlayer:692EBA448D201A0A:sceAvPlayerInit

## Description
boots to black screen

## Screenshots
![image](https://user-images.githubusercontent.com/28079950/210886693-3856a85f-0436-45bc-a66c-bcbc0573f96a.png)

**Comment by and468860** [comment]
nid:libSceVideodec2:4670E26DC1823CAC:sceVideodec2QueryComputeMemoryInfo

**Comment by ArbestRi** [comment]
```
[h264 @ 0000000005f12ac0] Invalid NAL unit size (-637514655 > 16).
[h264 @ 0000000005f12ac0] Error splitting the input into NAL units.
```
Crashes after that message.

**Comment by ArbestRi** [comment]
@gandalfthewhite19890404 add label `fmv-crash`.

**Comment by Kagamma** [comment]
`Invalid NAL unit size` indicates something is wrong with either the video, or ffmpeg itself so `fmv-crash` is suitable.

**Comment by gandalfthewhite19890404** [comment]
Retest

**Comment by ArbestRi** [comment]
With latest update, it goes much further. I got a some screenshots to cover here:
![Screenshot_20230203_042845](https://user-images.githubusercontent.com/86171223/216735032-74ce2459-a3e7-4beb-bac7-854b83a661d0.png)
![Screenshot_20230203_042856](https://user-images.githubusercontent.com/86171223/216735036-108262cc-3927-43a9-a216-5cb63251b44f.png)
![Screenshot_20230203_042937](https://user-images.githubusercontent.com/86171223/216735039-218f98a5-2748-470d-bd5e-c100401f8f3c.png)

**Comment by Kagamma** [comment]
Retest fmv-palette

**Comment by gandalfthewhite19890404** [comment]
Retest with [029a293](https://github.com/red-prig/fpPS4/commit/029a2935c13f35c7a6915e4714fbcd781c198342)

### **Current status:**
Menus

### **Used hacks:**
DEPTH_DISABLE_HACK - fixes rendering
COMPUTE_DISABLE_HACK - allows to boot game
SKIP_UNKNOW_TILING - allows to proceed to menus

### **Errors:**
An unhandled exception occurred at $000000010008EA33:
EAssertionFailed: Assertion failed (vHostBufferManager.pas, line 231)

### **Screenshots:**
![image](https://user-images.githubusercontent.com/24764335/224531812-04fdae8c-1a6a-43f6-86d7-40ae7a633882.png)
![image](https://user-images.githubusercontent.com/24764335/224531821-5a036c1b-fcdb-4a7d-9f0b-5871200539f3.png)
